-- ============================================
-- CREATE UBER EATS TABLES IN SNOWFLAKE
-- ============================================
-- Copy and paste this entire script into Snowflake

USE DATABASE PC_FIVETRAN_DB;
CREATE SCHEMA IF NOT EXISTS UBER_EATS;
USE SCHEMA UBER_EATS;

-- ============================================
-- 1. UBER_EATS_REPORTS (Report Metadata)
-- ============================================
CREATE TABLE IF NOT EXISTS UBER_EATS_REPORTS (
    WORKFLOW_ID VARCHAR PRIMARY KEY,
    REPORT_TYPE VARCHAR,
    STATUS VARCHAR,
    START_DATE DATE,
    END_DATE DATE,
    STORE_UUIDS VARIANT,
    DOWNLOAD_URL VARCHAR,
    CREATED_AT_UTC TIMESTAMP_NTZ,
    DOWNLOADED_AT_UTC TIMESTAMP_NTZ,
    _FIVETRAN_SYNCED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _FIVETRAN_DELETED BOOLEAN DEFAULT FALSE
);

-- ============================================
-- 2. UBER_EATS_REPORT_DATA (CSV Data Rows)
-- ============================================
CREATE TABLE IF NOT EXISTS UBER_EATS_REPORT_DATA (
    WORKFLOW_ID VARCHAR,
    REPORT_DATA VARIANT,
    _FIVETRAN_SYNCED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _FIVETRAN_DELETED BOOLEAN DEFAULT FALSE
);

-- ============================================
-- 3. UBER_EATS_STORES (Store Information)
-- ============================================
CREATE TABLE IF NOT EXISTS UBER_EATS_STORES (
    STORE_ID VARCHAR PRIMARY KEY,
    NAME VARCHAR,
    LOCATION_ADDRESS VARCHAR,
    LOCATION_CITY VARCHAR,
    LOCATION_STATE VARCHAR,
    LOCATION_POSTAL_CODE VARCHAR,
    LOCATION_COUNTRY VARCHAR,
    TIMEZONE VARCHAR,
    STATUS VARCHAR,
    WEB_URL VARCHAR,
    RAW_DATA VARIANT,
    _FIVETRAN_SYNCED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _FIVETRAN_DELETED BOOLEAN DEFAULT FALSE
);

-- ============================================
-- Grant Permissions
-- ============================================
GRANT ALL ON SCHEMA UBER_EATS TO ROLE PC_FIVETRAN_ROLE;
GRANT ALL ON TABLE UBER_EATS_REPORTS TO ROLE PC_FIVETRAN_ROLE;
GRANT ALL ON TABLE UBER_EATS_REPORT_DATA TO ROLE PC_FIVETRAN_ROLE;
GRANT ALL ON TABLE UBER_EATS_STORES TO ROLE PC_FIVETRAN_ROLE;

-- ============================================
-- Verify Tables Created
-- ============================================
SELECT 'UBER_EATS_REPORTS' AS table_name, COUNT(*) AS row_count FROM UBER_EATS_REPORTS
UNION ALL
SELECT 'UBER_EATS_REPORT_DATA', COUNT(*) FROM UBER_EATS_REPORT_DATA
UNION ALL
SELECT 'UBER_EATS_STORES', COUNT(*) FROM UBER_EATS_STORES;
