-- Create Uber Eats Tables (Matching Fivetran Schema)
-- Run this in Snowflake

USE DATABASE PC_FIVETRAN_DB;

-- Create UBER_EATS schema
CREATE SCHEMA IF NOT EXISTS UBER_EATS;
USE SCHEMA UBER_EATS;

-- 1. UBER_EATS_REPORTS table (matches Fivetran structure)
CREATE TABLE IF NOT EXISTS UBER_EATS_REPORTS (
    WORKFLOW_ID VARCHAR PRIMARY KEY,
    REPORT_TYPE VARCHAR,
    STATUS VARCHAR,
    START_DATE DATE,
    END_DATE DATE,
    STORE_UUIDS VARIANT,                -- JSON array of store IDs
    DOWNLOAD_URL VARCHAR,
    CREATED_AT_UTC TIMESTAMP_NTZ,
    DOWNLOADED_AT_UTC TIMESTAMP_NTZ,
    _FIVETRAN_SYNCED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _FIVETRAN_DELETED BOOLEAN DEFAULT FALSE
);

-- 2. UBER_EATS_REPORT_DATA table (stores CSV rows)
CREATE TABLE IF NOT EXISTS UBER_EATS_REPORT_DATA (
    WORKFLOW_ID VARCHAR,
    REPORT_DATA VARIANT,                -- Full CSV row as JSON
    _FIVETRAN_SYNCED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _FIVETRAN_DELETED BOOLEAN DEFAULT FALSE
);

-- 3. UBER_EATS_STORES table (optional - populated separately via Stores API)
CREATE TABLE IF NOT EXISTS UBER_EATS_STORES (
    STORE_ID VARCHAR PRIMARY KEY,
    NAME VARCHAR,
    LOCATION_ADDRESS VARCHAR,
    LOCATION_CITY VARCHAR,
    LOCATION_STATE VARCHAR,
    LOCATION_POSTAL_CODE VARCHAR,
    LOCATION_COUNTRY VARCHAR,
    LOCATION_LATITUDE FLOAT,
    LOCATION_LONGITUDE FLOAT,
    TIMEZONE VARCHAR,
    STATUS VARCHAR,
    WEB_URL VARCHAR,
    RAW_HERO_URL VARCHAR,
    AVG_PREP_TIME INT,
    POS_DATA_INTEGRATION_ENABLED BOOLEAN,
    LOCATION_ADDRESS_2 VARCHAR,
    _FIVETRAN_SYNCED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _FIVETRAN_DELETED BOOLEAN DEFAULT FALSE
);

-- Grant permissions
GRANT ALL ON SCHEMA UBER_EATS TO ROLE PC_FIVETRAN_ROLE;
GRANT ALL ON TABLE UBER_EATS_REPORTS TO ROLE PC_FIVETRAN_ROLE;
GRANT ALL ON TABLE UBER_EATS_REPORT_DATA TO ROLE PC_FIVETRAN_ROLE;
GRANT ALL ON TABLE UBER_EATS_STORES TO ROLE PC_FIVETRAN_ROLE;

-- Verify tables exist
SELECT 'UBER_EATS_REPORTS' AS table_name, COUNT(*) AS row_count FROM UBER_EATS_REPORTS
UNION ALL
SELECT 'UBER_EATS_REPORT_DATA', COUNT(*) FROM UBER_EATS_REPORT_DATA
UNION ALL
SELECT 'UBER_EATS_STORES', COUNT(*) FROM UBER_EATS_STORES;

-- Sample query: View reports with downloaded CSV data
SELECT 
    r.WORKFLOW_ID,
    r.REPORT_TYPE,
    r.START_DATE,
    r.END_DATE,
    r.STATUS,
    r.DOWNLOADED_AT_UTC,
    r._FIVETRAN_SYNCED,
    COUNT(d.WORKFLOW_ID) AS csv_row_count
FROM UBER_EATS_REPORTS r
LEFT JOIN UBER_EATS_REPORT_DATA d ON r.WORKFLOW_ID = d.WORKFLOW_ID
GROUP BY 1, 2, 3, 4, 5, 6, 7
ORDER BY r._FIVETRAN_SYNCED DESC;

-- Sample query: Flatten CSV data (DBT model pattern)
SELECT 
    r.WORKFLOW_ID,
    r.START_DATE,
    r.END_DATE,
    d.REPORT_DATA:"Store Name"::VARCHAR AS STORE_NAME,
    d.REPORT_DATA:"Shop ID"::VARCHAR AS SHOP_ID,
    d.REPORT_DATA:"Store ID"::VARCHAR AS STORE_ID,
    d.REPORT_DATA:"Order Count"::INT AS ORDER_COUNT,
    d.REPORT_DATA:"Sales (incl. tax)"::FLOAT AS SALES_INCL_TAX,
    d.REPORT_DATA:"Marketplace Fee"::FLOAT AS MARKETPLACE_FEE,
    d.REPORT_DATA:"Total payout"::FLOAT AS TOTAL_PAYOUT
FROM UBER_EATS_REPORTS r
JOIN UBER_EATS_REPORT_DATA d ON r.WORKFLOW_ID = d.WORKFLOW_ID
WHERE r.REPORT_TYPE = 'FINANCE_SUMMARY_REPORT'
LIMIT 10;
